docs/index.md, docs/planejamento.md
Neste pull request, realizou-se: 
* Adição e correção do versionamento
* Documentação sobre os outros repositorios do tembici no github
=> #1 Adição dos versionamentos e tembici no github

docs/planejamento/planejamento.md, docs/políticas/politicas.md
Criação da política de contribuição
=> Politica de contribuicao

docs/planejamento.md
Foram adicionadas as definições de metodologias. Descrevemos o que são as metodologias ágeis e o Scrum.
=> #2 -Metodologias Adicionadas

docs/apresentacoes.md, docs/index.md, docs/planejamento.md, docs/pre-rastreabilidade.md
=> 1 others tembici add responsability

docs/pre-rastreabilidade.md
=> #10-Adicao do 5W2H e referencias em pre-rastreabilidade

docs/elicitacao/elicitacao.md
=> #16 Criação de personas

docs/elicitacao/brainstorm.md, docs/elicitacao/introspeccao.md, docs/elicitacao/personas.md, docs/elicitacao/questionario.md, docs/index.md, docs/planejamento/planejamento.md, docs/pre-rastreabilidade/5w2h.md, docs/pre-rastreabilidade/rich-picture.md, docs/priorizacao/priorizacao.md
Adição de links clicáveis nos requisitos e referencias para a melhor rastreabilidade
#27
=> #27 WONTFIX - Adicionar links clicáveis

docs/pre-rastreabilidade/rich-picture.md
Adição de rich picture da funcionalidade de assinatura
HOTFIX #30 Adição Rich Picture Planos
=> HOTFIX - Adição Rich Picture Planos

docs/modelagem/especificacao_suplementar.md, docs/modelo.md, mkdocs.yml
O presente Pull Request está sendo aberto para adição da especificação suplementar ao projeto
[#34](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/34)
=> #34 Modelagem -> Especificação Suplementar

docs/modelagem/cenarios.md, mkdocs.yml
Este PR está sendo aberto a fim de adicionar o arquivo de Cenários ao projeto
[#38](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/38)
=> Criação de Cenários

docs/modelagem/lexicos.md
Este PR está sendo aberto a fim de adicionar o link para referenciar os léxicos citados em outrosa tabelas
[HOTFIX#41](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/41)
=> HOTFIX - Busca pelos lexicos

docs/modelagem/backlog/product_backlog.md, mkdocs.yml
Este PR está sendo aberto a fim adicionar no projeto o documento do backlog do produto
[#46](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/46)
=> #46 Criaçao do product backlog

docs/modelagem/backlog/historias_de_usuario.md
Issue para adição das Histórias de Usuário no Backlog
=> #46 Historias de usuário

docs/atas/ata_1503.md, docs/atas/ata_modelo.md, docs/elicitacao/tecnicas/brainstorm.md, docs/elicitacao/tecnicas/questionario.md, docs/modelagem/lexicos.md, docs/planejamento/cronograma.md, mkdocs.yml
Está iPR ssue destina-se a correções nos artefatos existentes
#49
=> 49 correções artefatos

docs/analise/verificacao/casos_de_uso.md, mkdocs.yml
PR está sendo aberto para que o artefato o qual apresenta a verificação seja adicionado à wiki.
[#51](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/51)
=> 51 verificação dos casos de uso

docs/analise/verificacao/cenarios.md, docs/analise/verificacao/richPicture.md, mkdocs.yml
=> Analyse richpicture and scenes

docs/modelagem/backlog/product_backlog.md, docs/pos-rastreabilidade/forward-from.md
HOTFIX no artefato Forward From
=> HOTFIX - Links no Forward From

docs/elicitacao/priorizacao/moscow.md, docs/elicitacao/tecnicas/introspeccao.md, docs/pos-rastreabilidade/forward-from.md
Adição de requisitos que estavam faltando na elicitação e consequentemente na pós-rastreabilidade
=> HOTFIX Adição de novos requisitos

docs/analise/validacao/viewpoint.md, mkdocs.yml
PR está sendo aberto para que o artefato o qual apresenta a criação do artefato Viewpoint seja adicionado a wiki.
[#84](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/84)
- Por se tratar de um artefato novo, não coloquei a pré-visualização.
=> #84 - Artefato Viewpoint

docs/analise/verificacao/richPicture.md, mkdocs.yml
PR está sendo aberto para que o artefato o qual apresenta a adição de itens faltantes no checklist do artefato de verificação do Rich Picture, além de outras pequenas melhorias.
[#85](https://github.com/Requisitos-de-Software/2021.2-Tembici/issues/85)
=> #85 - Artefato corrigido

docs/modelagem/backlog/historias_de_usuario.md, docs/modelagem/backlog/product_backlog.md, docs/pos-rastreabilidade/forward-from.md
=> HOTFIX - Revisão Backlog
